import HeroPic from "./types/heroPic";
import Product from "./types/product";

export const heroPic: HeroPic[] = [
    {
        id: 1,
        bgImg: "/hero_two.jpg",
        title: "Men’s fashion",
        items: "355 items",
    },
    {
        id: 2,
        bgImg: "/hero_three.jpg",
        title: "Kid’s fashion",
        items: "273 items",
    },
    {
        id: 3,
        bgImg: "/hero_four.jpg",
        title: "Cosmetics",
        items: "159 items",
    },
    {
        id: 4,
        bgImg: "/hero_five.jpg",
        title: "Accessories",
        items: "792 items",
    },
];

export const products: Product[] = [
    {
        _id: "prod_7a9b2c3d4e",
        title: "Premium Cotton Oxford Shirt",
        description: "Classic button-down oxford shirt in breathable cotton",
        price: 79.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL", "XXL"],
        bestSeller: true,
        rating: 4.8,
    },
    {
        _id: "prod_1x2y3z4w5",
        title: "Slim Fit Chino Pants",
        description: "Versatile chino pants with stretch comfort",
        price: 69.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "bottomwears",
        size: ["30x32", "32x32", "34x32", "36x32"],
        bestSeller: false,
        rating: 4.5,
    },
    {
        _id: "prod_8k9l0m1n2",
        title: "Floral Summer Dress",
        description: "Lightweight floral print dress perfect for summer",
        price: 89.99,
        images: ["/products/", "/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["XS", "S", "M", "L"],
        bestSeller: true,
        rating: 4.9,
    },
    {
        _id: "prod_3f4g5h6i7",
        title: "Kids Dinosaur T-Shirt",
        description: "Fun dinosaur print t-shirt for children",
        price: 24.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_9q0r1s2t3",
        title: "High-Waist Yoga Leggings",
        description: "Compression leggings with phone pocket",
        price: 54.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "bottomwears",
        size: ["XS", "S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.6,
    },
    {
        _id: "prod_4u5v6w7x8",
        title: "Men's Casual Blazer",
        description: "Modern fit blazer for casual occasions",
        price: 129.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["38R", "40R", "42R", "44R"],
        bestSeller: false,
        rating: 4.4,
    },
    {
        _id: "prod_2b3c4d5e6",
        title: "Pleated Midi Skirt",
        description: "Elegant pleated skirt in versatile black",
        price: 59.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "bottomwears",
        size: ["XS", "S", "M", "L"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_5y6z7a8b9",
        title: "Kids Denim Overalls",
        description: "Durable denim overalls for active kids",
        price: 39.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: false,
        rating: 4.5,
    },
    {
        _id: "prod_6c7d8e9f0",
        title: "Men's Polo Shirt",
        description: "Classic fit polo in premium pique cotton",
        price: 44.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_7g8h9i0j1",
        title: "Women's Cardigan",
        description: "Soft knit cardigan for layering",
        price: 49.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["S", "M", "L"],
        bestSeller: false,
        rating: 4.2,
    },
    {
        _id: "prod_8k9l0m1n2",
        title: "Cargo Shorts",
        description: "Multi-pocket cargo shorts for casual wear",
        price: 34.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "bottomwears",
        size: ["30", "32", "34", "36"],
        bestSeller: false,
        rating: 4.1,
    },
    {
        _id: "prod_9o0p1q2r3",
        title: "Floral Blouse",
        description: "Lightweight floral print blouse",
        price: 39.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["XS", "S", "M", "L"],
        bestSeller: true,
        rating: 4.6,
    },
    {
        _id: "prod_1s2t3u4v5",
        title: "Kids Winter Jacket",
        description: "Warm padded jacket for winter",
        price: 69.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["3T", "4T", "5T", "6T"],
        bestSeller: true,
        rating: 4.8,
    },
    {
        _id: "prod_2w3x4y5z6",
        title: "Denim Jacket",
        description: "Classic denim jacket with modern fit",
        price: 79.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_3a4b5c6d7",
        title: "Pencil Skirt",
        description: "Professional pencil skirt for office wear",
        price: 49.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "bottomwears",
        size: ["2", "4", "6", "8", "10"],
        bestSeller: false,
        rating: 4.4,
    },
    {
        _id: "prod_4e5f6g7h8",
        title: "Kids Summer Shorts",
        description: "Comfortable cotton shorts for summer",
        price: 19.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_5i6j7k8l9",
        title: "V-Neck Sweater",
        description: "Classic v-neck sweater in merino wool",
        price: 89.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.5,
    },
    {
        _id: "prod_6m7n8o9p0",
        title: "Maxi Dress",
        description: "Flowing maxi dress for special occasions",
        price: 99.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["XS", "S", "M", "L"],
        bestSeller: true,
        rating: 4.9,
    },
    {
        _id: "prod_7q8r9s0t1",
        title: "Kids Party Dress",
        description: "Adorable party dress for special events",
        price: 44.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: true,
        rating: 4.8,
    },
    {
        _id: "prod_8u9v0w1x2",
        title: "Leather Jacket",
        description: "Classic leather motorcycle jacket",
        price: 199.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_9y0z1a2b3",
        title: "Wide-Leg Pants",
        description: "Trendy high-waist wide-leg pants",
        price: 69.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "bottomwears",
        size: ["XS", "S", "M", "L"],
        bestSeller: false,
        rating: 4.4,
    },
    {
        _id: "prod_1c2d3e4f5",
        title: "Kids School Uniform",
        description: "Complete school uniform set",
        price: 49.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["4", "5", "6", "7", "8"],
        bestSeller: true,
        rating: 4.6,
    },
    {
        _id: "prod_2g3h4i5j6",
        title: "Dress Shirt",
        description: "Non-iron dress shirt for formal occasions",
        price: 59.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["15/32", "15.5/33", "16/34", "16.5/35"],
        bestSeller: true,
        rating: 4.5,
    },
    {
        _id: "prod_3k4l5m6n7",
        title: "Wrap Dress",
        description: "Flattering wrap dress for all occasions",
        price: 79.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["XS", "S", "M", "L"],
        bestSeller: true,
        rating: 4.8,
    },
    {
        _id: "prod_4o5p6q7r8",
        title: "Kids Rain Jacket",
        description: "Waterproof rain jacket with hood",
        price: 34.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_5s6t7u8v9",
        title: "Athletic Shorts",
        description: "Quick-dry performance shorts",
        price: 29.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "bottomwears",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.2,
    },
    {
        _id: "prod_6w7x8y9z0",
        title: "Silk Blouse",
        description: "Luxurious silk blouse for work",
        price: 89.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "topwear",
        size: ["XS", "S", "M", "L"],
        bestSeller: false,
        rating: 4.6,
    },
    {
        _id: "prod_7a8b9c0d1",
        title: "Kids Sweater",
        description: "Cozy knit sweater for children",
        price: 39.99,
        images: ["/products/"],
        category: "Kids",
        subCategory: "kidswear",
        size: ["2T", "3T", "4T", "5T"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_8e9f0g1h2",
        title: "Linen Shirt",
        description: "Breathable linen shirt for summer",
        price: 69.99,
        images: ["/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.5,
    },
    {
        _id: "prod_9i0j1k2l3",
        title: "Denim Skirt",
        description: "Classic denim mini skirt",
        price: 44.99,
        images: ["/products/"],
        category: "Women",
        subCategory: "bottomwears",
        size: ["XS", "S", "M", "L"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_1a2b3c4d5e",
        title: "Casual Linen Blazer",
        description: "Stylish blazer made from lightweight linen fabric",
        price: 129.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "outerwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.6,
    },
    {
        _id: "prod_2b3c4d5e6f",
        title: "Slim Fit Denim Jeans",
        description: "Modern slim fit jeans crafted from premium denim",
        price: 89.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "bottomwear",
        size: ["28", "30", "32", "34", "36"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_3c4d5e6f7g",
        title: "Cotton Polo Shirt",
        description: "Comfortable cotton polo shirt for casual wear",
        price: 49.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.5,
    },
    {
        _id: "prod_4d5e6f7g8h",
        title: "Wool Blend Suit Jacket",
        description: "Elegant suit jacket designed for formal occasions",
        price: 199.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "outerwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.4,
    },
    {
        _id: "prod_5e6f7g8h9i",
        title: "Sporty Running Shoes",
        description: "High-performance running shoes with cushioned soles",
        price: 119.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "footwear",
        size: ["7", "8", "9", "10", "11", "12"],
        bestSeller: true,
        rating: 4.9,
    },
    {
        _id: "prod_6f7g8h9i0j",
        title: "Leather Belt",
        description: "Classic leather belt with durable metal buckle",
        price: 39.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "accessories",
        size: ["30", "32", "34", "36", "38"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_7g8h9i0j1k",
        title: "Flannel Plaid Shirt",
        description: "Warm and stylish flannel shirt perfect for autumn",
        price: 69.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL", "XXL"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_8h9i0j1k2l",
        title: "Knitted Wool Sweater",
        description: "Soft and cozy sweater made from pure wool",
        price: 99.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.6,
    },
    {
        _id: "prod_9i0j1k2l3m",
        title: "Cotton Trousers",
        description: "Comfortable trousers made from breathable cotton",
        price: 79.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "bottomwear",
        size: ["28", "30", "32", "34", "36"],
        bestSeller: true,
        rating: 4.5,
    },
    {
        _id: "prod_0j1k2l3m4n",
        title: "Canvas Backpack",
        description: "Durable canvas backpack with multiple compartments",
        price: 59.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "bags",
        size: ["One Size"],
        bestSeller: false,
        rating: 4.4,
    },
    {
        _id: "prod_1k2l3m4n5o",
        title: "Smart Leather Watch",
        description: "Fashionable leather watch with modern features",
        price: 149.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "accessories",
        size: ["One Size"],
        bestSeller: true,
        rating: 4.8,
    },
    {
        _id: "prod_2l3m4n5o6p",
        title: "Sports Socks Pack",
        description: "Pack of moisture-wicking sports socks",
        price: 29.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "footwear",
        size: ["S", "M", "L"],
        bestSeller: false,
        rating: 4.3,
    },
    {
        _id: "prod_3m4n5o6p7q",
        title: "Denim Jacket",
        description: "Trendy denim jacket suitable for casual outings",
        price: 109.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "outerwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_4n5o6p7q8r",
        title: "Cotton Hoodie",
        description: "Comfortable hoodie with drawstring hood",
        price: 89.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL", "XXL"],
        bestSeller: false,
        rating: 4.6,
    },
    {
        _id: "prod_5o6p7q8r9s",
        title: "Formal Dress Shoes",
        description: "Polished leather dress shoes for formal events",
        price: 139.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "footwear",
        size: ["7", "8", "9", "10", "11", "12"],
        bestSeller: true,
        rating: 4.9,
    },
    {
        _id: "prod_6p7q8r9s0t",
        title: "Silk Tie Collection",
        description: "Set of silk ties in various patterns and colors",
        price: 69.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "accessories",
        size: ["One Size"],
        bestSeller: false,
        rating: 4.5,
    },
    {
        _id: "prod_7q8r9s0t1u",
        title: "Cargo Pants",
        description: "Practical cargo pants with multiple pockets",
        price: 99.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "bottomwear",
        size: ["28", "30", "32", "34", "36"],
        bestSeller: true,
        rating: 4.7,
    },
    {
        _id: "prod_8r9s0t1u2v",
        title: "Puffer Coat",
        description: "Insulated puffer coat for cold weather",
        price: 179.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "outerwear",
        size: ["S", "M", "L", "XL"],
        bestSeller: false,
        rating: 4.6,
    },
    {
        _id: "prod_9s0t1u2v3w",
        title: "Graphic Tee",
        description: "Bold graphic tee with vibrant print",
        price: 39.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "topwear",
        size: ["S", "M", "L", "XL", "XXL"],
        bestSeller: true,
        rating: 4.5,
    },
    {
        _id: "prod_0t1u2v3w4x",
        title: "Leather Wallet",
        description: "Compact leather wallet with RFID protection",
        price: 79.99,
        images: ["/products/", "/products/"],
        category: "Men",
        subCategory: "accessories",
        size: ["One Size"],
        bestSeller: false,
        rating: 4.4,
    },
];
